management:

  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  endpoint:
    health:
      show-details: always      # 디테일
      show-components: always   # 간략
    shutdown:
      enabled: true # 특정 엔드포인트 활성화 : management.endpoint.{엔드포인트명}.enabled=true

  endpoints:
    web:
      exposure:
        include: "*" # 모든 엔드 포인트를 웹에 노출
        exclude: "env,beans"
    jmx:
      exposure:
        include: "health,info"

# info 속성 추가
info:
  app:
    name: hello-actuator
    company: hahaha         